"""
Collector: Service Principal Sign-In Logs

Endpoint: GET /auditLogs/servicePrincipalSignIns
Requires:  AuditLog.Read.All

Collects sign-in events generated by service principals and managed identities
(i.e. OAuth app tokens, client credentials, and MSI). These are separate from
user interactive sign-ins and capture:

  - App-to-app and daemon authentication flows
  - Client secret vs certificate credential usage
  - Managed identity token acquisitions
  - Resource access by OAuth apps (which resource/API was targeted)

Key IOCs surfaced:
  - Failed SP authentication (wrong secret, expired cert, permission denied)
  - Client secret credential use (secrets are phishable; certs are preferred)
  - Authentication from a public IP (SP auth should normally come from known
    cloud/infrastructure egress ranges)
  - Unusually large number of failures for a single app (may indicate
    credential stuffing or a misconfigured app being abused)
  - Authentication to sensitive resources (e.g. Microsoft Graph, Exchange)

Why this matters:
  After gaining initial access, attackers frequently pivot to OAuth app tokens:
    1. They consent to a malicious app (OAuth phishing) — then sign in AS the app
    2. They extract a client secret from source code or Key Vault
    3. They register a new app and use it as a backdoor
  SP sign-ins are the evidence trail for all three scenarios, yet they are a
  completely separate log stream from user sign-ins and are commonly overlooked.
"""

from __future__ import annotations

from collections import defaultdict
from datetime import datetime
from typing import Any

from cirrus.collectors.base import GRAPH_BASE, GraphCollector
from cirrus.utils.helpers import is_private_ip

# ── Sensitive Microsoft resources — flag SP auth targeting these ──────────────
# These APIs grant broad access; SP auth against them warrants attention.
_SENSITIVE_RESOURCE_IDS: frozenset[str] = frozenset({
    "00000003-0000-0000-c000-000000000000",  # Microsoft Graph
    "00000002-0000-0ff1-ce00-000000000000",  # Exchange Online (EWS)
    "00000003-0000-0ff1-ce00-000000000000",  # SharePoint Online
    "00000002-0000-0000-c000-000000000000",  # Azure AD Graph (legacy)
    "797f4846-ba00-4fd7-ba43-dac1f8f63013",  # Azure Service Management
    "cfa8b339-82a2-471a-a3c9-0fc0be7a4093",  # Azure Key Vault
})

_SENSITIVE_RESOURCE_NAMES: frozenset[str] = frozenset({
    "microsoft graph",
    "exchange online",
    "office 365 exchange online",
    "sharepoint online",
    "azure key vault",
    "azure service management",
    "windows azure service management api",
})


def _flag_sp_signin(record: dict) -> list[str]:
    """
    Analyse a single service principal sign-in record and return IOC flags.
    """
    flags: list[str] = []

    # ── Failed authentication ──────────────────────────────────────────────────
    status = record.get("status") or {}
    error_code = status.get("errorCode", 0)
    if error_code != 0:
        reason = status.get("failureReason") or f"errorCode={error_code}"
        flags.append(f"FAILED_SP_AUTH:{reason}")

    # ── Credential type: client secret is riskier than certificate ────────────
    cred_type = record.get("servicePrincipalCredentialType") or ""
    if cred_type.lower() == "clientsecret":
        flags.append("CLIENT_SECRET_CREDENTIAL")
    elif cred_type.lower() == "certificate":
        flags.append("CERTIFICATE_CREDENTIAL")

    # ── IP address — public IPs warrant threat intel lookups ──────────────────
    ip = record.get("ipAddress") or ""
    if ip and not is_private_ip(ip):
        flags.append(f"PUBLIC_IP:{ip}")

    # ── Sensitive resource access ─────────────────────────────────────────────
    resource_id = record.get("resourceId") or ""
    resource_name = (record.get("resourceDisplayName") or "").lower().strip()
    if resource_id in _SENSITIVE_RESOURCE_IDS:
        flags.append(f"SENSITIVE_RESOURCE:{record.get('resourceDisplayName') or resource_id}")
    elif resource_name and resource_name in _SENSITIVE_RESOURCE_NAMES:
        flags.append(f"SENSITIVE_RESOURCE:{record.get('resourceDisplayName')}")

    # ── Location ──────────────────────────────────────────────────────────────
    location = record.get("location") or {}
    country = location.get("countryOrRegion") or ""
    if country:
        flags.append(f"COUNTRY:{country}")

    # ── Managed identity ──────────────────────────────────────────────────────
    # Managed identity sign-ins should only come from the assigned Azure resource.
    # A managed identity authenticating from an unexpected IP is suspicious.
    if record.get("managedIdentityType"):
        flags.append(f"MANAGED_IDENTITY:{record.get('managedIdentityType')}")

    return flags


def _detect_auth_failures(records: list[dict]) -> None:
    """
    Cross-record detection: flag apps with a high failure rate.

    If a single app has >= 10 failed sign-ins this may indicate credential
    stuffing or a misconfigured/hijacked app. Appends HIGH_FAILURE_RATE flag
    directly to all failing records for that app.
    """
    failure_counts: dict[str, int] = {}
    for record in records:
        if any(f.startswith("FAILED_SP_AUTH:") for f in record.get("_iocFlags", [])):
            app_id = record.get("appId") or record.get("servicePrincipalId") or "unknown"
            failure_counts[app_id] = failure_counts.get(app_id, 0) + 1

    high_failure_apps = {app_id for app_id, count in failure_counts.items() if count >= 10}

    for record in records:
        app_id = record.get("appId") or record.get("servicePrincipalId") or "unknown"
        if app_id in high_failure_apps:
            count = failure_counts[app_id]
            record["_iocFlags"].append(f"HIGH_FAILURE_RATE:{count}_failures")


def _detect_sp_anomalies(records: list[dict]) -> None:
    """
    Cross-record anomaly detection for service principal sign-ins.

    1. Multi-country authentication — an SP authenticating from 3+ distinct
       countries is unusual for normal cloud infrastructure (which tends to
       egress from fixed regions). Flags SP_MULTI_COUNTRY_AUTH.

    2. Authentication volume spike — if a single SP has a day with >5× the
       average daily auth count across the window, flag SP_AUTH_SPIKE. This
       surfaces compromised service principals being used for bulk operations.
    """
    # Group by app ID
    by_app: dict[str, list[dict]] = defaultdict(list)
    for r in records:
        app_id = r.get("appId") or r.get("servicePrincipalId") or "unknown"
        by_app[app_id].append(r)

    for app_id, app_records in by_app.items():
        # --- Multi-country detection ---
        countries: set[str] = set()
        for r in app_records:
            c = (r.get("location") or {}).get("countryOrRegion") or ""
            if c:
                countries.add(c)
        if len(countries) >= 3:
            country_list = ", ".join(sorted(countries))
            flag = f"SP_MULTI_COUNTRY_AUTH:{len(countries)}_countries:{country_list}"
            for r in app_records:
                r["_iocFlags"].append(flag)

        # --- Daily volume spike detection ---
        day_counts: dict[str, int] = defaultdict(int)
        for r in app_records:
            ts = r.get("createdDateTime") or ""
            day = ts[:10]  # YYYY-MM-DD
            if day:
                day_counts[day] += 1

        if len(day_counts) >= 2:
            avg_per_day = len(app_records) / len(day_counts)
            spike_threshold = max(avg_per_day * 5, 50)  # 5× average, minimum 50
            for day, count in day_counts.items():
                if count >= spike_threshold:
                    spike_flag = f"SP_AUTH_SPIKE:{count}_auths_on_{day}_(avg_{avg_per_day:.0f})"
                    for r in app_records:
                        if (r.get("createdDateTime") or "").startswith(day):
                            r["_iocFlags"].append(spike_flag)


class SPSignInLogsCollector(GraphCollector):
    """
    Collect service principal / managed identity sign-in logs from Entra ID.

    These are the sign-ins performed by *apps and services*, not by users.
    Captured separately from user interactive sign-ins at a different endpoint.
    """

    name = "sp_signin_logs"

    def collect(
        self,
        days: int = 30,
        start_dt: datetime | None = None,
        end_dt: datetime | None = None,
        app_ids: list[str] | None = None,
    ) -> list[dict]:
        """
        Collect SP sign-in logs, annotating each record with IOC flags.

        Args:
            days:     How many days back to collect (default 30).
                      Ignored when start_dt is provided.
            start_dt: Explicit collection start (UTC). Overrides days.
            end_dt:   Explicit collection end (UTC). Adds an upper bound filter.
            app_ids:  Optional list of app/SP IDs to filter on. None = all apps.

        Returns list of SP sign-in event dicts, each with a _iocFlags list.
        """
        self._require_license(
            "p1",
            "Service principal sign-in logs (/auditLogs/servicePrincipalSignIns) "
            "require Entra ID P1 or higher.",
        )

        filters = self._build_date_filter(start_dt, end_dt, days)

        if app_ids:
            id_filters = " or ".join(f"appId eq '{a}'" for a in app_ids)
            filters.append(f"({id_filters})")

        params: dict[str, Any] = {
            "$filter": " and ".join(filters),
            "$top": 999,
        }

        # Strip ConsistencyLevel for this call — standard filters only,
        # no advanced queries needed.  Sending it routes to the premium
        # backend and returns 403 on non-P1 tenants.
        self.session.headers.pop("ConsistencyLevel", None)
        try:
            records = self._collect_all(
                f"{GRAPH_BASE}/auditLogs/servicePrincipalSignIns", params
            )
        finally:
            self.session.headers["ConsistencyLevel"] = "eventual"

        # Per-record flagging
        for record in records:
            record["_iocFlags"] = _flag_sp_signin(record)

        # Cross-record: high failure rate detection
        _detect_auth_failures(records)

        # Cross-record: multi-country auth and daily volume spike detection
        _detect_sp_anomalies(records)

        return records
